[project]
name = "rl-stock-predictor"
version = "0.1.0"
description = ""
authors = [
    {name = "LipeTuga",email = "mie10010@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "stable-baselines3[extra] (>=2.6.0,<3.0.0)",
    "gym (>=0.26.2,<0.27.0)",
    "yfinance (>=0.2.61,<0.3.0)",
    "notebook (>=7.4.2,<8.0.0)",
    "shimmy (>=2.0.0,<3.0.0)"
]

[tool.poetry]
packages = [{include = "rl_stock_predictor", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
